blank_issues_enabled: true
contact_links:
  - name: Pregunta / Discusión
    url: https://github.com/nlebovits/censo-argentino-qgis/discussions
    about: Haz preguntas o discute ideas antes de abrir un issue
